---
{{- if index .Values "apps" "cert-manager" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cert-manager-claiv-umbrella
    repoURL: 'https://kayiplar-org.github.io/kayiplar-helm/'
    targetRevision: "0.2.1"
    helm:
      releaseName: cert-manager-claiv-umbrella
      values: |

        cert-manager:
          installCRDs: true
          namespace: cert-manager

        cert-manager-webhook-hetzner:
          groupName: acme.claiv.de

        # for hetzner api key
        secrets:
          - name: hetzner-api-key
            namespace: cert-manager
            {{- with index .Values "apps" "cert-manager" "spec" "secrets" "hetzner-api-key" "encryptedData" }}
            encryptedData:
              {{- range $key, $value := . }}
              {{ $key }}: {{ $value }}
              {{- end }}
            {{- end}}
            type: Opaque

        # issue certificate for claiv.de
          cluster-issuer:
            - type: letsencrypt
              name: prod-acme-cluster-issuer-claiv-de
              email: {{ index .Values "apps" "cert-manager" "spec" "issuer" "letsencrypt" "contact" "email" }}
              hetznerwebhook:
                enabled: true
                name: cert-manager-webhook-hetzner
              solvers:
                - dns01:
                    webhook:
                      groupName: {{ index .Values "apps" "cert-manager" "spec" "issuer" "letsencrypt" "groupName" }}
                      solverName: hetzner
                      config:
                        secretName: hetzner-api-key
                        zoneName: {{ index .Values "apps" "cert-manager" "spec" "issuer" "letsencrypt" "zoneName" }}
                        apiUrl: https://dns.hetzner.com/api/v1
              certificates:
                - name: auth-ctl-claiv-de-tls-certs
                  subject:
                    organizations:
                      - Claivolution GmbH
                  dnsNames:
                    - 'auth.CC_CLUSTER_SUBDOMAIN'

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}