---
{{- if index .Values "apps" "cert-manager" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cert-manager-claiv-umbrella
    repoURL: 'https://kayiplar-org.github.io/kayiplar-helm/'
    targetRevision: "0.2.8"
    helm:
      releaseName: cert-manager
      values: |

        cert-manager:
          installCRDs: true
          namespace: cert-manager
          fullnameOverride: cert-manager

        cert-manager-webhook-hetzner:
          groupName: acme.claiv.de
          fullnameOverride: webhook-hetzner

        hetzner-webhook:
          enabled: true
          name: webhook-hetzner
          groupName: acme.claiv.de
          zoneName: claiv.de
          secretKeyRef: 
            name: {{ index .Values "apps" "cert-manager" "spec" "secretKeyRef" "name" }}
            key: {{ index .Values "apps" "cert-manager" "spec" "secretKeyRef" "key" }}

        {{- with index .Values "apps" "cert-manager" "spec" "environment" }}
        environment: staging
        {{- end}}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - FailOnSharedResource=false
{{- end }}