---
{{- if .Values.apps.memgraph.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memgraph
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: memgraph
    repoURL: 'https://kayiplar-org.github.io/kayiplar-helm/'
    targetRevision: 0.0.1
    helm:
      releaseName: memgraph
      values: |

        replicas: 1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: memgraph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - FailOnSharedResource=false
{{- end }}