---
{{- if .Values.apps.minio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: minio
    repoURL: 'https://charts.min.io/'
    targetRevision: "4.0.12"
    helm:
      releaseName: minio
      values: |

        minio:
          persistence:
            enabled: true
            size: 1Ti

          buckets:
              # Name of the bucket
            - name: qi-tissue
              # Policy to be set on the
              # bucket [none|download|upload|public]
              policy: none
              # Purge if bucket exists already
              purge: false
              # set versioning for
              # bucket [true|false]
              versioning: true

          serviceAccount:
            create: true
            ## The name of the service account to use. If 'create' is 'true', a service account with that name
            ## will be created.
            name: "minio-sa"

          replicas: 2 #CC_CLUSTER_SIZE

          resources:
            requests:
              memory: 2Gi

          existingSecret: {{ index .Values "apps" "minio" "spec" "secretKeyRef" "name" }}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - FailOnSharedResource=false
{{- end }}