---
{{- if .Values.apps.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik-claiv-umbrella
    repoURL: 'https://kayiplar-org.github.io/kayiplar-helm/'
    targetRevision: {{ index .Values "apps" "traefik" "targetRevision" }}
    helm:
      releaseName: traefik
      values: |

        traefik:
          providers:
            kubernetesCRD:
              enabled: true
              allowCrossNamespace: true

        # example forward-auth config
        forward-auth:
          enabled: true

        middlewares:
          allow-all-origin:
            enabled: true
          allow-cors:
            enabled: true # origin will be https://qia.{base-domain} . If needed, a list should be passed here

        # example base domain
        base-domain: {{ index .Values "apps" "traefik" "spec" "host" }}

        ## pre-defined routes
        ingressRoutes:
          forward-auth:
            enabled: true
            domain-prefix: auth
          claiv:
            enabled: true
            domain-prefix: qia  # domain for claiv apps => qia.kayi.claiv.de
          argocd:
            enabled: true
            domain-prefix: argocd # domain for argocd => argocd.kayi.claiv.de
            service:
              name: argocd-claiv-server
              namespace: argocd
              port: 80

        certificate:
          issuer: prod-acme-cluster-issuer-claiv-de # ClusterIssuer of your cert-manager instance


  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - FailOnSharedResource=false
{{- end }}