---
{{- if .Values.apps.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik-claiv-umbrella
    repoURL: 'https://kayiplar-org.github.io/kayiplar-helm/'
    targetRevision: {{ index .Values "apps" "traefik" "targetRevision" }}
    helm:
      releaseName: traefik-claiv-umbrella
      values: |

        host: {{ index .Values "apps" "traefik" "spec" "host" }}

        traefik:
          providers:
            kubernetesCRD:
              enabled: true
              allowCrossNamespace: true

        secrets:
          - name: traefik-forward-auth-secrets
            namespace: kube-system
            {{- with index .Values "apps" "traefik" "spec" "secrets" "traefik-forward-auth-secrets" "encryptedData"  }}
            encryptedData:
              {{- range $key, $value := . }}
              {{ $key }}: {{ $value }}
              {{- end }}
            {{- end}}
            labels:
              app: traefik-forward-auth

        # example forward-auth config
        #{{- with index .Values "apps" "traefik" "spec" "forward-auth" }}
        #forwardauth:
        #  enabled: {{ index .Values "apps" "traefik" "spec" "forward-auth" "enabled" }}
        #{{- end}}
        forwardauth:
          enabled: true
        ## pre-defined routes
        ingressRoutes:
          claiv:
            enabled: true
          argocd:
            enabled: true
            service:
              name: argocd-claiv-server
              namespace: argocd
              port: 80
            path:
              prefix: /argocd

        certificate:
          name: auth-ctl-claiv-de-tls-certs
          issuer: prod-acme-cluster-issuer-claiv-de


  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    - FailOnSharedResource=false
{{- end }}