---
{{- if .Values.apps.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik-claiv-umbrella
    repoURL: 'https://kayiplar-org.github.io/kayiplar-helm/'
    targetRevision: "0.1.4"
    helm:
      releaseName: traefik-claiv-umbrella
      values: |

        host: {{ index .Values "apps" "traefik" "spec" "host" }}

        traefik:
          providers:
            kubernetesCRD:
              enabled: true
              allowCrossNamespace: true

        secrets:
          - name: traefik-forward-auth-secrets
            namespace: kube-system
            {{- with index .Values "apps" "traefik" "spec" "secrets" "traefik-forward-auth-secrets" "encryptedData"  }}
            encryptedData:
              {{- range $key, $value := . }}
              {{ $key }}: {{ $value }}
              {{- end }}
            {{- end}}
            labels:
              app: traefik-forward-auth

        # example forward-auth config
        forwardauth:
          enable: true

          ## pre-defined routes
          ingressRoutes:
            claiv:
              enable: true
            argocd:
              enable: true
              service:
                name: argocd-claiv-server
                namespace: argocd
                port: 80
              path:
                prefix: /argocd

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}