---
{{- if .Values.apps.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik-claiv-umbrella
    repoURL: 'https://kayiplar-org.github.io/kayiplar-helm/'
    targetRevision: "0.1.2"
    helm:
      releaseName: traefik-claiv-umbrella
      values: |

        traefik:
          providers:
            kubernetesCRD:
              enabled: true
              allowCrossNamespace: true

        secrets:
          - name: traefik-forward-auth-secrets
            namespace: kube-system
            {{- with index .Values "apps" "traefik" "spec" "secrets" "traefik-forward-auth-secrets" "encryptedData"  }}
            encryptedData:
              {{- range $key, $value := . }}
              {{ $key }}: {{ $value }}
              {{- end }}
            {{- end}}
            labels:
              app: traefik-forward-auth

        # example forward-auth config
        forwardauth:
          enable: true

          ## secrets and env vars for deployment. Secrets in this case are oidc secrets
          deployment:
            replicas: 1
            strategy: Recreate
            spec:
              terminationGracePeriodSeconds: 60
              containers:
              - image: thomseddon/traefik-forward-auth:2
                name: traefik-forward-auth
                ports:
                - containerPort: 4181
                  protocol: TCP
                env:
                # INSECURE_COOKIE is required unless using https entrypoint
                - name: DOMAIN
                  value: "claiv.de,claivolution.de,qitissue.com"
                - name: COOKIE_DOMAIN
                  value: "claiv.de"
                - name: AUTH_HOST
                  value: "https://kc.claiv.de/auth/realms/claiv-auth"
                - name: DEFAULT_PROVIDER
                  value: oidc
                - name: INSECURE_COOKIE
                  value: "false"
                - name: LOG_LEVEL
                  value: "debug"
                - name: PROVIDERS_OIDC_ISSUER_URL
                  valueFrom:
                    secretKeyRef:
                      name: traefik-forward-auth-secrets
                      key: traefik-forward-auth-oidc-issuer-url
                - name: PROVIDERS_OIDC_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: traefik-forward-auth-secrets
                      key: traefik-forward-auth-oidc-client-id
                - name: PROVIDERS_OIDC_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: traefik-forward-auth-secrets
                      key: traefik-forward-auth-oidc-client-secret
                - name: SECRET
                  valueFrom:
                    secretKeyRef:
                      name: traefik-forward-auth-secrets
                      key: traefik-forward-auth-secret

          ## defined routes
          ingressRoutes:
            claiv:
              enable: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}