apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: clarence-ingressroute-websecure
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qia.CC_CLUSTER_SUBDOMAIN`) && PathPrefix(`/qia_ui_state.UiStateManager`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`qia.CC_CLUSTER_SUBDOMAIN`) && PathPrefix(`/qia_ui_state.UiStateManager`) && Method(`HEAD`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`qia.CC_CLUSTER_SUBDOMAIN`) && PathPrefix(`/qia_annotations.Annotations`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`qia.CC_CLUSTER_SUBDOMAIN`) && PathPrefix(`/qia_annotations.Annotations`) && Method(`HEAD`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`qia.CC_CLUSTER_SUBDOMAIN`) && PathPrefix(`/audio`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
        - name: traefik-forward-auth
    - match: Host(`qia.CC_CLUSTER_SUBDOMAIN`) && PathPrefix(`/audio`) && Method(`HEAD`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
        - name: traefik-forward-auth

  tls:
    secretName: qia-ctl-claiv-de-tls-certs
    domains:
      - main: qia.CC_CLUSTER_SUBDOMAIN

