---
{{- if .Values.ingressRoutes.argocd.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth-ingressroute-websecure
  namespace: kube-system
  labels:
    app: traefik
spec:
  routes:
  - match: Host(`{{ .Values.host }}`) && PathPrefix(`/argocd`)
    kind: Rule
    services:
    - name: {{ .Values.ingressRoutes.argocd.service.name }}
      namespace: {{ .Values.ingressRoutes.argocd.service.namespace }}
      port: {{ .Values.ingressRoutes.argocd.service.port }}
  tls:
    secretName: {{ .Values.certificate.name}}
    domains: 
    - main: {{ .Values.host }}
{{- end}}
---
{{- if .Values.ingressRoutes.argocd.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth-ingressroute-websecure
  namespace: kube-system
  labels:
    app: traefik
spec:
  routes:
  - match: HostRegexp(`{catchall:.*}`)
    kind: Rule 
    services:
    - name: {{ .Values.ingressRoutes.argocd.service.name }}
      namespace: {{ .Values.ingressRoutes.argocd.service.namespace }}
      port: {{ .Values.ingressRoutes.argocd.service.port }}
  - match: PathPrefix(`/`)
    kind: Rule 
    services:
    - name: {{ .Values.ingressRoutes.argocd.service.name }}
      namespace: {{ .Values.ingressRoutes.argocd.service.namespace }}
      port: {{ .Values.ingressRoutes.argocd.service.port }}
{{- end}}