{{- if .Values.ingressRoutes.claiv.enabled }}
{{- $baseDomain := index .Values "base-domain"}}
{{- $baseDomainSafeName := index .Values "base-domain" | replace "." "-" }}
{{- $qiaDomainPrefix :=  index .Values "ingressRoutes" "claiv" "domain-prefix" }}
{{- $qiaDomainPrefixSafeName :=  index .Values "ingressRoutes" "claiv" "domain-prefix" | replace "." "_"}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: clarence-ingressroute-websecure
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix(`/qia_ui_state.UiStateManager`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix(`/qia_ui_state.UiStateManager`) && Method(`HEAD`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain}}`) && PathPrefix(`/qia_annotations.Annotations`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix(`/qia_annotations.Annotations`) && Method(`HEAD`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
      - name: traefik-forward-auth
    - match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix(`/audio`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
        - name: traefik-forward-auth
    - match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix(`/audio`) && Method(`HEAD`)
      kind: Rule
      services:
        - name: clarence
          namespace: qia-cloud
          port: 8080
          scheme: h2c
      middlewares:
        - name: traefik-forward-auth

  tls:
    secretName: {{ $qiaDomainPrefixSafeName }}-{{ $baseDomainSafeName }}-cert
    domains: 
    - main: {{ $qiaDomainPrefix }}.{{ $baseDomain }}

{{- end }}