{{- if index .Values "forward-auth" "enabled" }}
{{- $baseDomain := index .Values "base-domain"}}
{{- $baseDomainSafeName := index .Values "base-domain" | replace "." "-" }}
{{- $fauthDomainPrefix :=  index .Values "ingressRoutes" "forward-auth" "domain-prefix" }}
{{- $fauthDomainPrefixSafeName :=  index .Values "ingressRoutes" "forward-auth" "domain-prefix" | replace "." "-" }}
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth-ingressroute-websecure
  namespace: kube-system
  labels:
    app: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`{{ $fauthDomainPrefix }}.{{ $baseDomain}}`)
    kind: Rule
    services:
    - name: traefik-forward-auth
      namespace: kube-system
      port: 4181
  tls:
    secretName: {{ $fauthDomainPrefixSafeName }}-{{ $baseDomainSafeName }}-cert
    domains: 
    - main: {{ $fauthDomainPrefix }}.{{ $baseDomain }}
{{- end}}

