#---
#{{- if .Values.ingressRoutes.argocd.enabled }}
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: argocd-ingressroute
#  namespace: kube-system
#  labels:
#    app: traefik
#spec:
#  routes:
#  - match: Host(`{{ .Values.host }}`) && PathPrefix(`/argocd`)
#    kind: Rule
#    services:
#    - name: {{ .Values.ingressRoutes.argocd.service.name }}
#      namespace: {{ .Values.ingressRoutes.argocd.service.namespace }}
#      port: {{ .Values.ingressRoutes.argocd.service.port }}
#  tls:
#    secretName: {{ .Values.certificate.name}}
#    domains: 
#    - main: {{ .Values.host }}
#{{- end}}
#---
#{{- if .Values.ingressRoutes.argocd.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-default
  namespace: kube-system
  labels:
    app: traefik
spec:
  tls: {}
  entrypoints:
    - web
    - websecure
  routes:
  - match: PathPrefix(`/`)
    kind: Rule 
    services:
    - name: {{ .Values.ingressRoutes.argocd.service.name }}
      namespace: {{ .Values.ingressRoutes.argocd.service.namespace }}
      port: {{ .Values.ingressRoutes.argocd.service.port }}
{{- end}}