{{- if .Values.ingressRoutes.argocd.enabled }}
{{- $baseDomain := index .Values "base-domain"}}
{{- $baseDomainSafeName := index .Values "base-domain" | replace "." "-" }}
{{- $argocdDomainPrefix :=  index .Values "ingressRoutes" "argocd" "domain-prefix" }}
{{- $argocdDomainPrefixSafeName :=  index .Values "ingressRoutes" "argocd" "domain-prefix" | replace "." "_"}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-argocd
  namespace: kube-system
  labels:
    app: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ $argocdDomainPrefix}}.{{ $baseDomain}}`)
    kind: Rule 
    services:
    - name: {{ .Values.ingressRoutes.argocd.service.name }}
      namespace: {{ .Values.ingressRoutes.argocd.service.namespace }}
      port: {{ .Values.ingressRoutes.argocd.service.port }}
    middlewares:
    - name: traefik-forward-auth
  tls:
    secretName: {{ $argocdDomainPrefixSafeName }}-{{ $baseDomainSafeName }}-cert
    domains: 
    - main: {{ $argocdDomainPrefix }}.{{ $baseDomain }}
{{- end}}