{{- if .Values.ingressRoutes.claiv.enabled }}
{{- $baseDomain := index .Values "base-domain"}}
{{- $baseDomainSafeName := index .Values "base-domain" | replace "." "-" }}
{{- $qiaDomainPrefix :=  index .Values "ingressRoutes" "claiv" "domain-prefix" }}
{{- $qiaDomainPrefixSafeName :=  index .Values "ingressRoutes" "claiv" "domain-prefix" | replace "." "_"}}
---
#=========================================
# HTTPS Section
#=========================================
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: macsiq-api-server-ingressroute-websecure
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix( `/api/v1/` )
    kind: Rule
    services:
    - name: macsiq-api-server
      namespace: qia-cloud
      port: 8080
    middlewares:
    - name: allow-cors-mw

  - kind: Rule
    match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix( `/api/v1/` ) && Method(`OPTIONS`)
    middlewares:
    - name: allow-cors-mw
    services:
    - name: macsiq-api-server
      namespace: qia-cloud
      port: 8080
  
  - kind: Rule
    match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix( `/api/v2/` )
    services:
    - name: macsiq-api-server
      namespace: qia-cloud
      port: 8080
    middlewares:
    - name: allow-cors-mw

  - kind: Rule
    match: Host(`{{ $qiaDomainPrefix }}.{{ $baseDomain }}`) && PathPrefix( `/api/v2/` ) && Method(`OPTIONS`)
    services:
    - name: macsiq-api-server
      namespace: qia-cloud
      port: 8080
    middlewares:
    - name: allow-cors-mw

  #
  #---------------------------------------------------------------------------------  
  tls:
    secretName: {{ $qiaDomainPrefixSafeName }}-{{ $baseDomainSafeName }}-cert
    domains: 
    - main: {{ $qiaDomainPrefix }}.{{ $baseDomain }}

{{- end}}