---
{{- if .Values.forwardauth.ingressRoutes.claiv.enable }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth-ingressroute-websecure
  namespace: kube-system
  labels:
    app: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.host }}`)
    kind: Rule
    services:
    - name: traefik-forward-auth
      namespace: kube-system
      port: 4181
  tls:
    secretName: {{ .Values.certificate.name}}
    domains: 
    - main: {{ .Values.host }}
{{- end}}