---
{{- if .Values.forwardauth.ingressRoutes.argocd.enable }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth-ingressroute-websecure
  namespace: kube-system
  labels:
    app: traefik
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.host }}`) && PathPrefix(`/argocd`)
    kind: Rule
    services:
    - name: {{ .Values.forwardauth.ingressRoutes.argocd.service.name }}
      namespace: {{ .Values.forwardauth.ingressRoutes.argocd.service.namespace }}
      port: {{ .Values.forwardauth.ingressRoutes.argocd.service.port }}
  tls:
    secretName: auth-ctl-claiv-de-tls-certs
    domains: 
    - main: {{ .Values.host }}
{{- end}}