{{- if index .Values "middlewares" "allow-all-origin" "enabled" }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: allow-all-origin
  namespace: kube-system
spec:
  headers:
    accessControlAllowOriginList: 
      - "*"
{{- end}}
{{- if index .Values "forward-auth" "enabled" }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: kube-system
spec:
  forwardAuth:
    address: http://traefik-forward-auth:4181
    authResponseHeaders:
      - X-Forwarded-User
{{- end}}
{{- if index .Values "forward-auth" "enabled" }}
---
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    port: "443"
    permanent: true
{{- end}}
{{- if index .Values "middlewares" "allow-cors" "enabled" }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: allow-cors-mw
  namespace: kube-system
spec:
  headers:
    accessControlAllowHeaders:
    - authorization
    accessControlAllowMethods:
    - GET
    - OPTIONS
    - PUT
    accessControlAllowOriginList:
    - https://{{ $qiaDomainPrefix }}.{{ $baseDomain }}
    addVaryHeader: true
{{- end}}