{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "passbolt-helm.fullname" . }}
  labels:
{{ include "passbolt-helm.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        {{- end }}
        backend:
        {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ template "passbolt-helm.fullname" . }}
            port:
              number: {{ .port | default 80 }}
        {{- else }}
          serviceName:  {{ template "passbolt-helm.fullname" . }}
          servicePort: {{ .Values.service.port | default "80" }}
        {{- end }}
{{- end }}
