---
{{- if .Values.apps.replicator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replicator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kubernetes-replicator
    repoURL: https://helm.mittwald.de
    targetRevision: {{ .Values.apps.replicator.targetRevision }}
    helm:
      releaseName: replicator
      values: |
        args: 
          - -allow-all=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
{{- end }}