{{- if .Values.vars }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.vars }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}