{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $resourceName := include "robustName" .Release.Name -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $resourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      {{- if not .Values.ingress.useDefaultCertificate }}
      secretName: {{ .Values.ingress.secretName | default (printf "tls-%s" $resourceName) }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" | quote }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ $resourceName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
