# example for claiv test cluster

apps:
  cert-manager:
    enabled: true
    spec:
      environment: staging
      secretKeyRef:
        name: hetzner-api-key
        key: api-key

  gitlab-runner:
    enabled: true
    spec:
      domain: gitlab.claiv.de
      secretKeyRef:
        name: gitlab-runner-secret

  jupyterhub:
    enabled: true
    spec:
      secretKeyRef:
        name: gitlab-token
        key: gitlab-token

  minio:
    enabled: true
    spec:
      secretKeyRef:
        name: minio-root-credentials

  nats:
    enabled: true

  memgraph:
    enabled: true

  traefik:
    enabled: false
    targetRevision: "0.2.44"
    spec:
      host: kayi.claiv.de