{{- if index .Values "qia" "apps" "qik" "enabled" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "qik"
  name: "qik"
  namespace: qia-cloud
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: "qik"
{{- end}}