{{- if index .Values "qia" "apps" "macsiqview-api-server" "enabled" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: macsiq-api-server
  name: macsiq-api-server
  namespace: qia-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: macsiq-api-server
  template:
    metadata:
      labels:
        app: macsiq-api-server
        actorSystemName: macsiq-api-server
    spec:
      imagePullSecrets:
        - name: "regcred"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - macsiq-api-server
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: macsiq-api-server
          image: registry.claiv.de/qi/services/qia_explorations/macsiqview_backend_api_scala_generated/api_server:{{ index .Values "qia" "apps" "macsiqview-api-server" "image-tag" }}
          # remove for real clusters, useful for minikube
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            # akka-management and bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MACSIQVIEW_CLOUD_URL
              value: "https://{{ .Values.qia.fullyQualifiedDomainName }}"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: QIK_HOST
              value: "qik.qia-cloud.svc.cluster.local"
            - name: QIK_PORT
              value: "8080"
            - name: S3_URL
              value: "http://minio.minio.svc.cluster.local:9000"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3creds
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3creds
                  key: secret-key
            - name: NATS_HOST
              value: "nats.nats.svc.cluster.local"
            - name: NATS_PORT
              value: "4222"
            - name: HTTP_HOST
              value: "0.0.0.0"
            - name: HTTP_PORT
              value: "8080"
            - name: PROCESSING_JOB_STREAM_NAME
              value: "processing_job_stream"
            {{- with index .Values "qia" "apps" "macsiqview-api-server" "extraEnv" }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
{{- end }}