---
{{- if .Values.qia.apps.doc.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qiadocs
  name: qiadocs
  namespace: qia-cloud
spec:
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: qiadocs
{{- end }}