{{- if index .Values "qia" "apps" "pyramid-worker" "enabled" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "pyramid-worker"
  name: "pyramid-worker"
  namespace: qia-cloud
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: "pyramid-worker"
{{- end}}