{{- range $secret := .Values.secrets}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{$secret.name}}
  namespace: {{$secret.namespace}}
spec:
  encryptedData:
    {{- range $key, $val := $secret.encryptedData}}
    {{ $key }}: {{ $val }}
    {{- end }}
  template:
    {{- with $secret.type }}
    type: {{$secret.type}}
    {{- end}}
    metadata:
      creationTimestamp: null
      {{- with $secret.labels }}
      labels:
        {{- range $key, $val := $secret.labels}}
        {{ $key }}: {{ $val }}
        {{- end }}
      {{- end}}
      {{- with $secret.annotations }}
      annotations:
        {{- range $key, $val := $secret.annotations}}
        {{ $key }}: {{ $val }}
        {{- end }}
      {{- end}}
      name: {{$secret.name}}
      namespace: {{$secret.namespace}}
      {{- with $secret.type }}
      {{- end}}
{{- end}}