gitlab-runner:
  ## https://docs.gitlab.com/runner/install/kubernetes.html
  gitlabUrl: https://gitlab.claiv.de/
  concurrent: 10
  checkInterval: 30
  rbac:
    create: true
    clusterWideAccess: true
  runners:
    config: |

      [[runners]]
        dns_search = ["gitlab.claiv.de"]

    image: debian:latest
    serviceAccountName: default
    secret: gitlab-runner-secret