#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name:  auth-ctl-claiv-de-tls-certs
#  namespace: kube-system
#spec:
#  # Secret names are always required.
#  secretName:  auth-ctl-claiv-de-tls-certs
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#  subject:
#    organizations:
#    - Claivolution GmbH
#  # At least one of a DNS Name, URI, or IP address is required.
#  dnsNames:
#  - {{ .Values.dnsName }}
#  # Issuer references are always required.
#  issuerRef:
#    name: prod-acme-cluster-issuer-claiv-de
#    # We can reference ClusterIssuers by changing the kind here.
#    # The default value is Issuer (i.e. a locally namespaced Issuer)
#    kind: ClusterIssuer
#
#{{- range $issuer := index .Values "cluster-issuer" }}
#{{- if eq $issuer.type "letsencrypt" }}
#{{- range $certificate := $issuer.certificates }}
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: {{ $certificate.name }}
#  namespace: kube-system
#spec:
#  # Secret names are always required.
#  secretName:  {{ $certificate.name }}
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#  {{- with $certificate.subject }}
#  subject:
#    {{- toYaml . | nindent 2 | indent 2 }}
#  {{- end }}
#  # At least one of a DNS Name, URI, or IP address is required.
#  {{- with $certificate.dnsNames }}
#  {{- range $name := $certificate.dnsNames}}
#  dnsNames:
#  - {{ $name | squote }}
#  {{- end }}
#  {{- end }}
#  # Issuer references are always required.
#  issuerRef:
#    name: {{ $issuer.name }}
#    # We can reference ClusterIssuers by changing the kind here.
#    # The default value is Issuer (i.e. a locally namespaced Issuer)
#    kind: ClusterIssuer
#{{- end }}
#{{- end }}
#{{- end }}