apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  auth-ctl-claiv-de-tls-certs
  namespace: kube-system
spec:
  # Secret names are always required.
  secretName:  auth-ctl-claiv-de-tls-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Claivolution GmbH
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - 'auth.CC_CLUSTER_SUBDOMAIN'
  # Issuer references are always required.
  issuerRef:
    name: prod-acme-cluster-issuer-claiv-de
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
