kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: cert-manager-allow-kube-sytem-rolebinding
 namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
roleRef:
 kind: Role
 name: cert-manager-allow-kube-sytem-role
 apiGroup: rbac.authorization.k8s.io
---
{{- range $issuer := index .Values "cluster-issuer" }}
{{if $issuer.hetznerwebhook.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ $issuer.hetznerwebhook.name}}
 namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: {{ $issuer.hetznerwebhook.name}}
  namespace: cert-manager
roleRef:
 kind: Role
 name: {{ $issuer.hetznerwebhook.name}}
 apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}