kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: kube-system
 name: cert-manager-allow-kube-sytem-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
{{- range $issuer := index .Values "cluster-issuer" }}
{{if $issuer.hetznerwebhook.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: cert-manager
 name: {{ $issuer.hetznerwebhook.name}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end}}
{{- end}}