kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: kube-system
 name: cert-manager-allow-kube-sytem-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
{{- if .Values.hetznerwebhook.enable }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: cert-manager
 name: cert-manager-webhook-hetzner
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end}}