argo-cd:
  nameOverride: argocd
  fullnameOverride: argocd

  crds:
    install: true

  server:
    service:
      type: NodePort 

    extraArgs:
    - --insecure

apps:
  replicator:
    enabled: true
    targetRevision: v2.7.3
  sealed-secrets-controller:
    enabled: true
    targetRevision: 2.6.9