jupyterhub:
  proxy:
    service:
      type: ClusterIP
  singleuser:
    defaultUrl: "/lab"
    uid: 0
    cmd: start-singleuser.sh
    image:
      name: jupyter/tensorflow-notebook
      tag: latest #6d42503c684f
    extraEnv:
      - name: GITLAB_TOKEN
        valueFrom:
          secretKeyRef:
            name: gitlab-token
            key: gitlab-token
      - name: GRANT_SUDO
        value: "yes"
      - name: NOTEBOOK_ARGS
        value: "--allow-root"
  hub:
    config:
      Authenticator:
        admin_users:
          - admin
      DummyAuthenticator:
        password: admin
      JupyterHub:
        authenticator_class: dummy