#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  creationTimestamp: null
#  name: james-jwt-key
#  namespace: james-mailserver
#spec:
#  encryptedData:
#    jwt_privatekey: {{ .Values.james.secret.jwtPrivateKey }}
#    jwt_publickey: {{ .Values.james.secret.jwtPublicKey }}
#  template:
#    metadata:
#      creationTimestamp: null
#      name: james-jwt-key
#      namespace: james-mailserver
#    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-cassandra-account-james
  namespace: james-mailserver
spec:
  encryptedData:
    james-password: {{ .Values.james.secret.cassandraPassword }}
    james-user: {{ .Values.james.secret.cassandraUser }}
  template:
    metadata:
      creationTimestamp: null
      name: db-cassandra-account-james
      namespace: james-mailserver
    type: Opaque
{{- if and (.Values.james.secret.esUser) (.Values.james.secret.esPassword) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-es-account-james
  namespace: james-mailserver
spec:
  encryptedData:
    james-password: {{ .Values.james.secret.esPassword }}
    james-user: {{ .Values.james.secret.esUser }}
  template:
    metadata:
      creationTimestamp: null
      name: db-es-account-james
      namespace: james-mailserver
    type: Opaque
---
{{- end}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dkim-private-key
  namespace: james-mailserver
spec:
  encryptedData:
    dkim.key: {{ .Values.james.secret.dkimPrivateKey }}
  template:
    metadata:
      creationTimestamp: null
      name: dkim-private-key
      namespace: james-mailserver
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-james-credentials
  namespace: james-mailserver
spec:
  encryptedData:
    OS_S3_ACCESSKEYID: {{ .Values.james.secret.s3.accessKeyId }}
    OS_S3_ENDPOINT: {{ .Values.james.secret.s3.endpoint }}
    OS_S3_REGION: {{ .Values.james.secret.s3.region }}
    OS_S3_SECRETKEY: {{ .Values.james.secret.s3.secretKey }}
  template:
    metadata:
      creationTimestamp: null
      name: s3-james-credentials
      namespace: james-mailserver
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-account-james
  namespace: james-mailserver
spec:
  encryptedData:
    rabbitmq-user: {{ .Values.james.secret.rabbitmqUser }}
    rabbitmq-password: {{ .Values.james.secret.rabbitmqPassword }}
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-account-james
      namespace: james-mailserver
    type: Opaque
