cert-manager:
  installCRDs: true
  namespace: cert-manager
  fullnameOverride: cert-manager

cert-manager-webhook-hetzner:
  groupName: acme.claiv.de
  fullnameOverride: webhook-hetzner


hetzner-webhook:
  enabled: true
  name: webhook-hetzner
  groupName: acme.claiv.de
  zoneName: claiv.de
  secretKeyRef: 
    name: hetzner-api-key
    key: api-key 

environment: prod