apiVersion: v2
name: qia-argocd-custom-install
description: A Helm chart for all qia custom-install application deployments.

type: application

version: 0.0.6

sources:
  - https://github.com/kayiplar-org/kayiplar-helm

maintainers:
  - name: Salih Kayiplar
    email: salih.kayiplar@gmail.com
    url: https://github.com/kayiplar